INSERT INTO products (
    name,
    category,
    eco_score,
    co2_gram,
    recyclability,
    alt_recommendation,
    explanation,
    material,
    is_reusable,
    is_single_use,
    recycled_content_percent,
    lifecycle_type
) VALUES
('Single-use Plastic Bottle', 'plastic bottle', 25, 150.0, 'Low', 'Use a reusable steel bottle', '', 'plastic', FALSE, TRUE, 0, 'single_use'),
('Paper Coffee Cup', 'paper cup', 40, 120.0, 'Medium', 'Choose a refillable coffee cup', '', 'paper-lined', FALSE, TRUE, 20, 'single_use'),
('LED Light Bulb', 'light bulb', 88, 35.0, 'Medium', 'Keep using energy-efficient LED bulbs', '', 'mixed electronics', TRUE, FALSE, 15, 'long_life'),
('Aluminum Can', 'aluminum can', 78, 45.0, 'High', 'Prefer recycled aluminum packaging', '', 'aluminum', FALSE, TRUE, 65, 'single_use_recyclable'),
('Disposable Cutlery', 'utensils', 20, 90.0, 'Low', 'Switch to reusable metal cutlery', '', 'plastic', FALSE, TRUE, 0, 'single_use'),
('Cotton T-shirt', 'fast fashion', 55, 700.0, 'Medium', 'Buy durable or second-hand clothing', '', 'cotton', TRUE, FALSE, 0, 'long_life'),
('Banana', 'food', 92, 18.0, 'Organic', 'Choose local and seasonal produce', '', 'organic', FALSE, TRUE, 0, 'biodegradable'),
('Glass Bottle', 'glass bottle', 74, 95.0, 'High', 'Return and refill when available', '', 'glass', TRUE, FALSE, 40, 'reusable'),
('Reusable Bottle', 'reusable bottle', 95, 12.0, 'High', 'Keep using reusable containers', '', 'stainless steel', TRUE, FALSE, 35, 'reusable'),
('Cloth Bag', 'bag', 93, 15.0, 'High', 'Carry a cloth bag for shopping', '', 'cloth', TRUE, FALSE, 60, 'reusable'),
('Plastic Bag', 'bag', 18, 80.0, 'Low', 'Use a reusable cloth bag', '', 'plastic', FALSE, TRUE, 0, 'single_use'),
('Fast Food Container', 'food packaging', 30, 130.0, 'Low', 'Choose dine-in or reusable containers', '', 'mixed plastic', FALSE, TRUE, 0, 'single_use'),
('Carton Milk', 'beverage carton', 70, 65.0, 'Medium', 'Prefer local milk with returnable packaging', '', 'beverage carton', FALSE, TRUE, 25, 'single_use_recyclable'),
('Refillable Coffee Cup', 'coffee cup', 96, 10.0, 'High', 'Use refillable cups for takeaway drinks', '', 'stainless steel', TRUE, FALSE, 30, 'refillable'),
('Recycled Paper Notebook', 'stationery', 90, 25.0, 'High', 'Choose 100% recycled paper products', '', 'recycled paper', TRUE, FALSE, 90, 'long_life'),
('Disposable Coffee Lid', 'coffee cup', 28, 75.0, 'Low', 'Carry a reusable cup with integrated lid', '', 'plastic', FALSE, TRUE, 0, 'single_use'),
('Stainless Steel Tumbler', 'coffee cup', 97, 9.0, 'High', 'Great choice. Keep reusing this tumbler.', '', 'stainless steel', TRUE, FALSE, 40, 'reusable'),
('Plastic Straw', 'utensils', 15, 42.0, 'Low', 'Skip straws or switch to reusable metal straws', '', 'plastic', FALSE, TRUE, 0, 'single_use'),
('Reusable Metal Straw', 'utensils', 94, 7.0, 'High', 'Great choice. Keep cleaning and reusing it.', '', 'stainless steel', TRUE, FALSE, 35, 'reusable'),
('Disposable Plastic Fork', 'utensils', 18, 58.0, 'Low', 'Use reusable metal cutlery', '', 'plastic', FALSE, TRUE, 0, 'single_use'),
('Reusable Cutlery Set', 'utensils', 95, 11.0, 'High', 'Great choice. Keep carrying your reusable set.', '', 'stainless steel', TRUE, FALSE, 30, 'reusable'),
('Styrofoam Food Box', 'food packaging', 12, 160.0, 'Low', 'Prefer reusable lunch containers or dine-in', '', 'polystyrene', FALSE, TRUE, 0, 'single_use'),
('Glass Lunch Container', 'food packaging', 92, 22.0, 'High', 'Great choice. Reuse this container regularly.', '', 'glass', TRUE, FALSE, 35, 'reusable'),
('Plastic Wrap', 'food packaging', 22, 48.0, 'Low', 'Use reusable silicone lids or beeswax wraps', '', 'plastic', FALSE, TRUE, 0, 'single_use'),
('Beeswax Wrap', 'food packaging', 89, 19.0, 'Medium', 'Great low-waste option. Keep reusing it.', '', 'beeswax cotton', TRUE, FALSE, 20, 'reusable'),
('Single-use Water Bottle Pack', 'plastic bottle', 14, 180.0, 'Low', 'Refill a reusable bottle with tap or filtered water', '', 'plastic', FALSE, TRUE, 0, 'single_use'),
('Insulated Reusable Bottle', 'reusable bottle', 97, 8.0, 'High', 'Excellent choice. Continue using refill stations.', '', 'stainless steel', TRUE, FALSE, 35, 'reusable'),
('Fast Fashion Polyester Shirt', 'fast fashion', 24, 820.0, 'Low', 'Choose durable natural fibers or second-hand clothing', '', 'polyester', FALSE, FALSE, 0, 'fast_fashion'),
('Second-hand Denim Jacket', 'slow fashion', 91, 34.0, 'High', 'Great choice. Extending clothing life lowers impact.', '', 'denim', TRUE, FALSE, 0, 'long_life'),
('Plastic Grocery Bag', 'bag', 16, 85.0, 'Low', 'Carry reusable cloth or jute shopping bags', '', 'plastic', FALSE, TRUE, 0, 'single_use'),
('Jute Shopping Bag', 'bag', 94, 14.0, 'High', 'Great choice. Reuse this bag for every shopping trip.', '', 'jute', TRUE, FALSE, 70, 'reusable'),
('Disposable Battery', 'electronics', 26, 66.0, 'Low', 'Use rechargeable batteries and proper recycling points', '', 'alkaline metal', FALSE, TRUE, 10, 'single_use'),
('Rechargeable Battery', 'electronics', 90, 21.0, 'Medium', 'Great choice. Recharge and reuse for longer life.', '', 'rechargeable metal', TRUE, FALSE, 20, 'reusable'),
('Plastic Toothbrush', 'personal care', 29, 40.0, 'Low', 'Choose replaceable-head or bamboo toothbrushes', '', 'plastic', FALSE, TRUE, 0, 'single_use'),
('Bamboo Toothbrush', 'personal care', 84, 18.0, 'Medium', 'Good choice. Compost handle where facilities exist.', '', 'bamboo', FALSE, TRUE, 5, 'biodegradable');
